ALTER TABLE `APPBS_USUARIOS_LOG`
CHANGE COLUMN `TEXTO1` `TEXTO1` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Valor de texto 1'  ,
CHANGE COLUMN `TEXTO2` `TEXTO2` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Valor de texto 2'  ,
CHANGE COLUMN `TEXTO3` `TEXTO3` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Valor de texto 3'  ,
CHANGE COLUMN `TEXTO4` `TEXTO4` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Valor de texto 4'  ,
CHANGE COLUMN `TEXTO5` `TEXTO5` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Valor de texto 5'  ;
