
CREATE TABLE `APPBS_LOOKUPS` (
  `ID_LOOKUP` varchar(30) NOT NULL COMMENT 'Id. del lookup',
  `NOMBRE` varchar(50) NOT NULL COMMENT 'Nombre',
  `EDITABLE` char(1) NOT NULL COMMENT 'Indica si es editable (S/N)',
  `ACTIVO` char(1) NOT NULL COMMENT 'Indica si esta activo (S/N)',
  PRIMARY KEY (`ID_LOOKUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Tabla para lista de lookups';

CREATE TABLE `APPBS_LOOKUPS_VALUES` (
  `ID_LOOKUP` varchar(30) NOT NULL COMMENT 'Id. del lookup',
  `ID_VALOR` varchar(100) NOT NULL COMMENT 'Id. del valor ',
  `NOMBRE` varchar(200) NOT NULL COMMENT 'Nombre visible',
  `ACTIVO` char(1) NOT NULL COMMENT 'Indica si esta activo (S/N)',
  PRIMARY KEY (`ID_LOOKUP`,`ID_VALOR`),
  CONSTRAINT `fk_APPBS_LOOKUPS_VALUES_1` FOREIGN KEY (`ID_LOOKUP`) REFERENCES `APPBS_LOOKUPS` (`ID_LOOKUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Valores de lookups';

SET @APPNAME='RUTAS';

INSERT INTO `APPBS_MENU` (`ID_APLICACION`, `ID_MENU`, `NOMBRE`, `ORDEN`, `ID_PADRE`, `TIPO_ENLACE`) VALUES (@APPNAME, 'APPBS_ADMIN_LOOKUPS', 'Lookups', '110', 'APPBS_ADMIN', 'L');

INSERT INTO `APPBS_MENU_PERFILES` (`ID_APLICACION`, `ID_MENU`, `ID_PERFIL`) VALUES (@APPNAME, 'APPBS_ADMIN_LOOKUPS', '1');
INSERT INTO `APPBS_MENU_PERFILES` (`ID_APLICACION`, `ID_MENU`, `ID_PERFIL`) VALUES (@APPNAME, 'APPBS_ADMIN_LOOKUPS', '2');





