DROP TABLE `APPBS_LOG`;
CREATE TABLE `APPBS_LOG` (
  `ID_LOG` int(11) NOT NULL AUTO_INCREMENT,
  `ID_APLICACION` varchar(10) NOT NULL DEFAULT '',
  `NIVEL` int(10) unsigned NOT NULL DEFAULT '4' COMMENT 'Nivel de Log',
  `TIPO` varchar(20) NOT NULL DEFAULT '' COMMENT 'Tipo',
  `FECHA` datetime NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT 'Fecha',
  `DATOS1` varchar(500) DEFAULT NULL COMMENT 'Datos',
  `DATOS2` varchar(500) DEFAULT NULL COMMENT 'Datos',
  `DATOS3` varchar(500) DEFAULT NULL COMMENT 'Datos',
  `DATOS4` varchar(500) DEFAULT NULL COMMENT 'Datos',
  `DATOS5` varchar(500) DEFAULT NULL COMMENT 'Datos',
  PRIMARY KEY (`ID_LOG`),
  KEY `Index_1` (`NIVEL`) USING BTREE,
  KEY `Index_2` (`TIPO`) USING BTREE,
  KEY `Index_3` (`FECHA`) USING BTREE,
  KEY `Index_4` (`ID_APLICACION`) USING BTREE,
  CONSTRAINT `fk_APPBS_LOG_1` FOREIGN KEY (`ID_APLICACION`) REFERENCES `APPBS_APLICACIONES` (`ID_APLICACION`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COMMENT='Log de eventos';