ALTER TABLE `APPBS_PARAMETROS_VALORES` DROP FOREIGN KEY `fk_APPBS_PARAMETROS_VALORES_1` ;
ALTER TABLE `APPBS_PARAMETROS_VALORES` ADD CONSTRAINT `fk_APPBS_PARAMETROS_VALORES_1` FOREIGN KEY (`ID_APLICACION` , `ID_PARAMETRO` )
  REFERENCES `APPBS_PARAMETROS` (`ID_APLICACION` , `ID_PARAMETRO` ) ON DELETE CASCADE ON UPDATE CASCADE;
