ALTER TABLE `APPEX_PAISES` ADD COLUMN `G_CODE` VARCHAR(100) NULL COMMENT 'Codigo asignado por Google Maps'  AFTER `ACTIVO` ;
ALTER TABLE `APPEX_PAISES` ADD COLUMN `GEOLOCALIZACION` VARCHAR(100) NULL COMMENT 'Coordenadas del pais'  AFTER `G_CODE` ;

ALTER TABLE `APPEX_PROVINCIAS` ADD COLUMN `G_CODE` VARCHAR(100) NULL COMMENT 'Codigo asignado por Google Maps'  AFTER `CP_PREFIX` ;

ALTER TABLE `APPEX_PROVINCIAS` ADD COLUMN `ID_COMUNIDAD` INT NULL  AFTER `ID_PROVINCIA` ;

CREATE TABLE `APPEX_COMUNIDADES` (
  `ID_COMUNIDAD` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Id. de la comunidad',
  `ID_PAIS` int(10) unsigned NOT NULL COMMENT 'Id. del pais',
  `NOMBRE` varchar(100) NOT NULL COMMENT 'Nombre',
  `G_CODE` varchar(45) DEFAULT NULL COMMENT 'Codigo asignado por Google Maps',
  PRIMARY KEY (`ID_COMUNIDAD`),
  KEY `fk_APPEX_COMUNIDADES_1` (`ID_PAIS`),
  CONSTRAINT `fk_APPEX_COMUNIDADES_1` FOREIGN KEY (`ID_PAIS`) REFERENCES `APPEX_PAISES` (`ID_PAIS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Comunidades / Regiones';

ALTER TABLE `APPEX_PROVINCIAS` CHANGE COLUMN `ID_COMUNIDAD` `ID_COMUNIDAD` INT(11) UNSIGNED NULL DEFAULT NULL;

