ALTER TABLE `APPBS_TABLAS` ADD COLUMN `EXTRA_UPDATE` VARCHAR(1000) NULL  AFTER `EXTRA_SELECT` ;
ALTER TABLE `APPBS_TABLAS` CHANGE COLUMN `XGROUP` `XGROUP` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Group by de la select'  ,
CHANGE COLUMN `EXTRA_WHERE` `EXTRA_WHERE` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Sincronizacion (WHERE)'  ,
CHANGE COLUMN `EXTRA_SELECT` `EXTRA_SELECT` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Sincronizacion (SELECT)'  ,
CHANGE COLUMN `EXTRA_UPDATE` `EXTRA_UPDATE` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Sincronizacion (WHERE en los updateDB)'  ;

ALTER TABLE `APPBS_TABLAS` ADD COLUMN `TRIGGERS` VARCHAR(500) NULL COMMENT 'Nombre de la clase Triggers'  AFTER `PARAM_4` ;

ALTER TABLE `APPBS_TABLAS` ADD COLUMN `DELETE_WHERE` VARCHAR(1000) NULL COMMENT 'Condicion para el DELETE'  AFTER `EXTRA_SELECT` ;
