ALTER TABLE `APPBS_CAMPOS` ADD COLUMN `ORG_FORMATO` VARCHAR(50) NULL COMMENT 'Formato del campo'  AFTER `ORG_TIPO` ;

ALTER TABLE `APPBS_CAMPOS` ADD COLUMN `PARAM_1` VARCHAR(100) NULL COMMENT 'Parametro 1'  AFTER `ORG_FORMATO` ;
ALTER TABLE `APPBS_CAMPOS` ADD COLUMN `PARAM_2` VARCHAR(100) NULL COMMENT 'Parametro 2'  AFTER `PARAM_1` ;
ALTER TABLE `APPBS_CAMPOS` ADD COLUMN `PARAM_3` VARCHAR(100) NULL COMMENT 'Parametro 3'  AFTER `PARAM_2` ;
ALTER TABLE `APPBS_CAMPOS` ADD COLUMN `PARAM_4` VARCHAR(100) NULL COMMENT 'Parametro 4'  AFTER `PARAM_3` ;

ALTER TABLE `APPBS_TABLAS` ADD COLUMN `PARAM_1` VARCHAR(100) NULL COMMENT 'Parametro 1'  AFTER `EXTRA_SELECT` ;
ALTER TABLE `APPBS_TABLAS` ADD COLUMN `PARAM_2` VARCHAR(100) NULL COMMENT 'Parametro 2'  AFTER `PARAM_1` ;
ALTER TABLE `APPBS_TABLAS` ADD COLUMN `PARAM_3` VARCHAR(100) NULL COMMENT 'Parametro 3'  AFTER `PARAM_2` ;
ALTER TABLE `APPBS_TABLAS` ADD COLUMN `PARAM_4` VARCHAR(100) NULL COMMENT 'Parametro 4'  AFTER `PARAM_3` ;
