ALTER TABLE `APPBS_USUARIOS` ADD COLUMN `COOKIE` VARCHAR(45) NULL COMMENT 'Cookie del usuario'  AFTER `LOG_LEVEL` ;

ALTER TABLE `APPBS_USUARIOS_PERFILES` DROP FOREIGN KEY `fk_APPBS_USUARIOS_PERFILES_1` ;
ALTER TABLE `APPBS_USUARIOS_PERFILES` ADD CONSTRAINT `fk_APPBS_USUARIOS_PERFILES_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `APPBS_USUARIOS` (`ID_USUARIO` ) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- 09/01/2012
--
ALTER TABLE `APPBS_USUARIOS` ADD COLUMN `ID_IDIOMA` INT(11) UNSIGNED NULL COMMENT 'Id. del ultimo idioma utilizado'  AFTER `COOKIE` ;
