CREATE SEQUENCE "APPBS_CAMPOS_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 901 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "APPBS_TABLAS_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 321 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "APPBS_USUARIOS_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 36401 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "HIBERNATE_SEQUENCE" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1181 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "APPBS_APLICACIONES"
  (
    "ID_APLICACION" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "NOMBRE"        VARCHAR2(50 BYTE) NOT NULL ENABLE,
    CONSTRAINT "APPBS_APLICACIONES_PK" PRIMARY KEY ("ID_APLICACION") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "APPBS_TABLAS"
  (
    "ID_TABLA"     NUMBER NOT NULL ENABLE,
    "NOMBRE"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ORIGEN"       VARCHAR2(50 BYTE),
    "REPLICA"      VARCHAR2(100 BYTE),
    "XSELECT"      VARCHAR2(200 BYTE),
    "XFROM"        VARCHAR2(200 BYTE),
    "XWHERE"       VARCHAR2(200 BYTE),
    "XGROUP"       VARCHAR2(200 BYTE),
    "EXTRA_WHERE"  VARCHAR2(200 BYTE),
    "EXTRA_SELECT" VARCHAR2(200 BYTE),
    "PARAM_1"      VARCHAR2(100 BYTE),
    "PARAM_2"      VARCHAR2(100 BYTE),
    "PARAM_3"      VARCHAR2(100 BYTE),
    "PARAM_4"      VARCHAR2(100 BYTE),
    "CREACION"     NUMBER(*,0),
    "SINCRO"       NUMBER(*,0),
    "VERSION"      NUMBER(*,0),
    "ORDEN"        NUMBER(*,0),
    CONSTRAINT "APPBS_TABLAS_PK" PRIMARY KEY ("ID_TABLA") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE OR REPLACE TRIGGER "TRG_APPBS_TABLAS_INSERT" BEFORE
  INSERT ON APPBS_TABLAS FOR EACH ROW BEGIN
  SELECT appbs_tablas_seq.nextval INTO :new.id_tabla FROM dual;
END;
/
ALTER TRIGGER "TRG_APPBS_TABLAS_INSERT" ENABLE;

CREATE TABLE "APPBS_CAMPOS"
  (
    "ID_CAMPO"       NUMBER NOT NULL ENABLE,
    "ID_TABLA"       NUMBER NOT NULL ENABLE,
    "NOMBRE"         VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "TIPO"           VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "ORDEN"          NUMBER NOT NULL ENABLE,
    "LLAVE_PRIMARIA" VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "ORG_NOMBRE"     VARCHAR2(100 BYTE),
    "ORG_CAMPO"      VARCHAR2(20 BYTE),
    "ORG_TIPO"       VARCHAR2(1 BYTE),
    "ORG_FORMATO"    VARCHAR2(50 BYTE),
    "PARAM_1"        VARCHAR2(100 BYTE),
    "PARAM_2"        VARCHAR2(100 BYTE),
    "PARAM_3"        VARCHAR2(100 BYTE),
    "PARAM_4"        VARCHAR2(100 BYTE),
    "EXPORTABLE"     VARCHAR2(1 BYTE),
    "FUENTE"         VARCHAR2(1 BYTE),
    "FUENTE_VALOR1"  VARCHAR2(500 BYTE),
    "FUENTE_VALOR2"  VARCHAR2(20 BYTE),
    CONSTRAINT "APPBS_CAMPOS_PK" PRIMARY KEY ("ID_CAMPO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_CAMPOS_TABLAS" FOREIGN KEY ("ID_TABLA") REFERENCES "APPBS_TABLAS" ("ID_TABLA") ON
  DELETE CASCADE ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE OR REPLACE TRIGGER "TRG_APPBS_CAMPOS_INSERT" BEFORE
  INSERT ON APPBS_CAMPOS FOR EACH ROW BEGIN
  SELECT appbs_campos_seq.nextval INTO :new.id_campo FROM dual;
END;
/
ALTER TRIGGER "TRG_APPBS_CAMPOS_INSERT" ENABLE;


CREATE TABLE "APPBS_FOREINGKEYS"
  (
    "ID_KEY"     NUMBER(15,0) NOT NULL ENABLE,
    "NOMBRE"     VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "EXPORTABLE" NUMBER(*,0),
    "ID_TABLA"   NUMBER,
    CONSTRAINT "APPBS_FOREINGKEYS_PK" PRIMARY KEY ("ID_KEY") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "APPBS_FOREINGKEYS_APPBS_T_FK1" FOREIGN KEY ("ID_TABLA") REFERENCES "APPBS_TABLAS" ("ID_TABLA") ON
  DELETE CASCADE ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "APPBS_FOREINGKEYS_VALUES"
  (
    "ID_KEY"      NUMBER(15,0) NOT NULL ENABLE,
    "ID_TABLA"    NUMBER NOT NULL ENABLE,
    "ID_CAMPO"    NUMBER NOT NULL ENABLE,
    "ID_REFTABLA" NUMBER,
    "ID_REFCAMPO" NUMBER,
    CONSTRAINT "APPBS_FOREINKEYS_VALUES_PK" PRIMARY KEY ("ID_KEY", "ID_TABLA", "ID_CAMPO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "APPBS_FOREINGKEYS_VALUES__FK1" FOREIGN KEY ("ID_KEY") REFERENCES "APPBS_FOREINGKEYS" ("ID_KEY") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "APPBS_UPDATES"
  (
    "ID_UPDATE" NUMBER NOT NULL ENABLE,
    "ID_TABLA"  NUMBER,
    "FECHA" DATE,
    "INT_PK1"   NUMBER,
    "INT_PK2"   NUMBER,
    "INT_PK3"   NUMBER,
    "STR_PK1"   VARCHAR2(100 BYTE),
    "STR_PK2"   VARCHAR2(20 BYTE),
    "STR_PK3"   VARCHAR2(100 BYTE),
    "OPERACION" VARCHAR2(1 BYTE),
    CONSTRAINT "APPBS_UPDATES_PK" PRIMARY KEY ("ID_UPDATE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "APPBS_UPDATES_APPBS_TABLA_FK1" FOREIGN KEY ("ID_TABLA") REFERENCES "APPBS_TABLAS" ("ID_TABLA") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "APPBS_LOG"
  (
    "ID_LOG"        NUMBER NOT NULL ENABLE,
    "ID_APLICACION" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "NIVEL"         NUMBER NOT NULL ENABLE,
    "TIPO"          VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "FECHA" DATE NOT NULL ENABLE,
    "LOG" VARCHAR2(2000 BYTE),
    CONSTRAINT "APPBS_LOG_PK" PRIMARY KEY ("ID_LOG") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_LOG_APLICACIONES" FOREIGN KEY ("ID_APLICACION") REFERENCES "APPBS_APLICACIONES" ("ID_APLICACION") ON
  DELETE CASCADE ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "APPBS_LOG_INDEX1" ON "APPBS_LOG"
  (
    "ID_APLICACION"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "APPBS_LOG_INDEX2" ON "APPBS_LOG"
  (
    "NIVEL"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "APPBS_LOG_INDEX3" ON "APPBS_LOG"
  (
    "TIPO"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "APPBS_LOG_INDEX4" ON "APPBS_LOG"
  (
    "FECHA"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "APPBS_LOG_PK" ON "APPBS_LOG"
  (
    "ID_LOG"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;


CREATE TABLE "APPBS_LOOKUPS"
  (
    "ID_LOOKUP" VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "NOMBRE"    VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "EDITABLE"  VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "ACTIVO"    VARCHAR2(1 BYTE) NOT NULL ENABLE,
    CONSTRAINT "APPEX_LOCKUPS_PK" PRIMARY KEY ("ID_LOOKUP") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "APPBS_LOOKUPS_VALUES"
  (
    "ID_LOOKUP" VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "ID_VALOR"  VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "NOMBRE"    VARCHAR2(200 BYTE) NOT NULL ENABLE,
    "ACTIVO"    VARCHAR2(1 BYTE) NOT NULL ENABLE,
    CONSTRAINT "APPEX_LOOKUP_VALUES_PK" PRIMARY KEY ("ID_LOOKUP", "ID_VALOR") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "APPEX_LOOKUP_VALUES_APPEX_FK1" FOREIGN KEY ("ID_LOOKUP", "ID_VALOR") REFERENCES "APPBS_LOOKUPS_VALUES" ("ID_LOOKUP", "ID_VALOR") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

  CREATE TABLE "APPBS_PARAMETROS"
  (
    "ID_APLICACION" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "ID_PARAMETRO"  VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "NOMBRE"        VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "VALOR"         VARCHAR2(2000 BYTE) NOT NULL ENABLE,
    "TIPO"          VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "MIN_INT"       NUMBER,
    "MAX_INT"       NUMBER,
    "MIN_FLOAT"     NUMBER,
    "MAX_FLOAT"     NUMBER,
    "MIN_DATE" DATE,
    "MAX_DATE" DATE,
    "CHECKRANGE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "EDIT"       VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "VISIBLE"    VARCHAR2(1 BYTE) NOT NULL ENABLE,
    CONSTRAINT "APPBS_PARAMETROS_PK" PRIMARY KEY ("ID_APLICACION", "ID_PARAMETRO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_PARAMETROS_APLICACIONES" FOREIGN KEY ("ID_APLICACION") REFERENCES "APPBS_APLICACIONES" ("ID_APLICACION") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "APPBS_PARAMETROS_VALORES"
  (
    "ID_APLICACION" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "ID_PARAMETRO"  VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "ID_VALOR"      NUMBER NOT NULL ENABLE,
    "NOMBRE"        VARCHAR2(45 BYTE) NOT NULL ENABLE,
    CONSTRAINT "APPBS_PARAMETROS_VALORES_PK" PRIMARY KEY ("ID_APLICACION", "ID_PARAMETRO", "ID_VALOR") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_PARAMETROS_VALORES_PARAM" FOREIGN KEY ("ID_APLICACION", "ID_PARAMETRO") REFERENCES "APPBS_PARAMETROS" ("ID_APLICACION", "ID_PARAMETRO") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

  CREATE TABLE "APPBS_PERFILES"
  (
    "ID_PERFIL" NUMBER NOT NULL ENABLE,
    "NOMBRE"    VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "TIPO"      VARCHAR2(50 BYTE),
    CONSTRAINT "APPBS_PERFILES_PK" PRIMARY KEY ("ID_PERFIL") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

  CREATE TABLE "APPBS_MENU"
  (
    "ID_APLICACION" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "ID_MENU"       VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "NOMBRE"        VARCHAR2(45 BYTE) NOT NULL ENABLE,
    "ORDEN"         NUMBER NOT NULL ENABLE,
    "ID_PADRE"      VARCHAR2(20 BYTE),
    "ENLACE"        VARCHAR2(100 BYTE),
    "TIPO_ENLACE"   VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "ATRIBUTO1"     VARCHAR2(100 BYTE),
    "ATRIBUTO2"     VARCHAR2(100 BYTE),
    "ATRIBUTO3"     VARCHAR2(100 BYTE),
    "ATRIBUTO4"     VARCHAR2(100 BYTE),
    "ATRIBUTO5"     VARCHAR2(100 BYTE),
    "ATRIBUTO6"     VARCHAR2(100 BYTE),
    "ATRIBUTO7"     VARCHAR2(100 BYTE),
    "ATRIBUTO8"     VARCHAR2(100 BYTE),
    "ATRIBUTO9"     VARCHAR2(100 BYTE),
    "ATRIBUTO10"    VARCHAR2(100 BYTE),
    CONSTRAINT "APPBS_MENU_PK" PRIMARY KEY ("ID_APLICACION", "ID_MENU") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_MENU_APLICACIONES" FOREIGN KEY ("ID_APLICACION") REFERENCES "APPBS_APLICACIONES" ("ID_APLICACION") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

  CREATE TABLE "APPBS_MENU_PERFILES"
  (
    "ID_APLICACION" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "ID_MENU"       VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "ID_PERFIL"     NUMBER NOT NULL ENABLE,
    CONSTRAINT "APPBS_MENU_PERFILES_PK" PRIMARY KEY ("ID_APLICACION", "ID_MENU", "ID_PERFIL") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_MENU_PERFILES_PERFILES" FOREIGN KEY ("ID_PERFIL") REFERENCES "APPBS_PERFILES" ("ID_PERFIL") ENABLE,
    CONSTRAINT "FK_MENU_PERFILES_MENU" FOREIGN KEY ("ID_APLICACION", "ID_MENU") REFERENCES "APPBS_MENU" ("ID_APLICACION", "ID_MENU") ON
  DELETE CASCADE ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;


  CREATE TABLE "APPBS_USUARIOS_TIPOS"
  (
    "ID_TIPO"     NUMBER NOT NULL ENABLE,
    "NOMBRE"      VARCHAR2(45 BYTE) NOT NULL ENABLE,
    "DESCRIPCION" VARCHAR2(150 BYTE),
    CONSTRAINT "APPBS_USUARIOS_TIPOS_PK" PRIMARY KEY ("ID_TIPO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

  CREATE TABLE "APPBS_USUARIOS"
  (
    "ID_USUARIO"  NUMBER NOT NULL ENABLE,
    "NOMBRE"      VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "LOGIN"       VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "CLAVE"       VARCHAR2(45 BYTE) NOT NULL ENABLE,
    "FAX"         VARCHAR2(45 BYTE),
    "TELEFONO"    VARCHAR2(45 BYTE),
    "MOVIL"       VARCHAR2(20 BYTE),
    "EMAIL"       VARCHAR2(100 BYTE),
    "PARAM_1"     VARCHAR2(50 BYTE),
    "PARAM_2"     VARCHAR2(50 BYTE),
    "PARAM_3"     VARCHAR2(50 BYTE),
    "PARAM_4"     VARCHAR2(50 BYTE),
    "INT_PARAM_1" NUMBER(15,0),
    "INT_PARAM_2" NUMBER(15,0),
    "INT_PARAM_3" NUMBER(15,0),
    "INT_PARAM_4" NUMBER(15,0),
    "TIPO"        NUMBER NOT NULL ENABLE,
    "FECHA_CREACION" DATE,
    "FECHA_CONEXION" DATE,
    "ACTIVO"    VARCHAR2(1 BYTE),
    "LOG_LEVEL" NUMBER(15,0),
    "COOKIE"    VARCHAR2(50 BYTE),
    CONSTRAINT "APPBS_USUARIOS_PK" PRIMARY KEY ("ID_USUARIO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_APPBS_USUARIOS_1" FOREIGN KEY ("TIPO") REFERENCES "APPBS_USUARIOS_TIPOS" ("ID_TIPO") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE OR REPLACE TRIGGER "TRG_APPBS_USARIOS_INSERT" BEFORE
  INSERT ON APPBS_USUARIOS FOR EACH ROW BEGIN
  SELECT appbs_usuarios_seq.nextval INTO :new.id_usuario FROM dual;
END;
/
ALTER TRIGGER "TRG_APPBS_USARIOS_INSERT" ENABLE;

CREATE TABLE "APPBS_USUARIOS_HIST_CLAVES"
  (
    "ID_USUARIO" NUMBER NOT NULL ENABLE,
    "CLAVE"      VARCHAR2(45 BYTE) NOT NULL ENABLE,
    "FECHA" DATE,
    CONSTRAINT "APPBS_USUARIOS_HIST_CLAVE_PK" PRIMARY KEY ("ID_USUARIO", "CLAVE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_APPBS_USUARIOS_HIST_CLAVE_1" FOREIGN KEY ("ID_USUARIO") REFERENCES "APPBS_USUARIOS" ("ID_USUARIO") ON
  DELETE CASCADE ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "APPBS_USUARIOS_LOG_LEGEND"
  (
    "ID_TIPO" NUMBER NOT NULL ENABLE,
    "NOMBRE"  VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "TEXTO"   VARCHAR2(200 BYTE) NOT NULL ENABLE,
    CONSTRAINT "APPBS_USUARIOS_LOG_LEGEND_PK" PRIMARY KEY ("ID_TIPO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "APPBS_USUARIOS_LOG"
  (
    "ID_USUARIO"    NUMBER NOT NULL ENABLE,
    "ID_APLICACION" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "ID_TIPO"       NUMBER NOT NULL ENABLE,
    "FECHA" TIMESTAMP (6) NOT NULL ENABLE,
    "NIVEL"     NUMBER NOT NULL ENABLE,
    "TEXTO1"    VARCHAR2(200 BYTE),
    "TEXTO2"    VARCHAR2(200 BYTE),
    "TEXTO3"    VARCHAR2(200 BYTE),
    "TEXTO4"    VARCHAR2(200 BYTE),
    "TEXTO5"    VARCHAR2(200 BYTE),
    "SESION_ID" VARCHAR2(50 BYTE),
    CONSTRAINT "APPBS_USUARIOS_LOG_PK" PRIMARY KEY ("ID_USUARIO", "ID_APLICACION", "ID_TIPO", "FECHA") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_APPBS_USUARIOS_LOG_1" FOREIGN KEY ("ID_APLICACION") REFERENCES "APPBS_APLICACIONES" ("ID_APLICACION") ENABLE,
    CONSTRAINT "FK_APPBS_USUARIOS_LOG_2" FOREIGN KEY ("ID_USUARIO") REFERENCES "APPBS_USUARIOS" ("ID_USUARIO") ON
  DELETE CASCADE ENABLE,
    CONSTRAINT "FK_APPBS_USUARIOS_LOG_3" FOREIGN KEY ("ID_TIPO") REFERENCES "APPBS_USUARIOS_LOG_LEGEND" ("ID_TIPO") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "APPBS_USUARIOS_LOG_INDEX1" ON "APPBS_USUARIOS_LOG"
  (
    "ID_USUARIO"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "APPBS_USUARIOS_LOG_INDEX2" ON "APPBS_USUARIOS_LOG"
  (
    "ID_APLICACION"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "APPBS_USUARIOS_LOG_INDEX3" ON "APPBS_USUARIOS_LOG"
  (
    "ID_TIPO"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "APPBS_USUARIOS_LOG_INDEX4" ON "APPBS_USUARIOS_LOG"
  (
    "FECHA"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "APPBS_USUARIOS_LOG_INDEX5" ON "APPBS_USUARIOS_LOG"
  (
    "NIVEL"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "APPBS_USUARIOS_LOG_PK" ON "APPBS_USUARIOS_LOG"
  (
    "ID_USUARIO", "ID_APLICACION", "ID_TIPO", "FECHA"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "APPBS_USUARIOS_PERFILES"
  (
    "ID_USUARIO"    NUMBER NOT NULL ENABLE,
    "ID_APLICACION" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "ID_PERFIL"     NUMBER NOT NULL ENABLE,
    CONSTRAINT "APPBS_USUARIOS_PERFILES_PK" PRIMARY KEY ("ID_USUARIO", "ID_APLICACION") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK_APPBS_USUARIOS_PERFILES_1" FOREIGN KEY ("ID_APLICACION") REFERENCES "APPBS_APLICACIONES" ("ID_APLICACION") ENABLE,
    CONSTRAINT "FK_APPBS_USUARIOS_PERFILES_3" FOREIGN KEY ("ID_USUARIO") REFERENCES "APPBS_USUARIOS" ("ID_USUARIO") ENABLE,
    CONSTRAINT "APPBS_USUARIOS_PERFILES_A_FK1" FOREIGN KEY ("ID_PERFIL") REFERENCES "APPBS_PERFILES" ("ID_PERFIL") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;